# Generated by Django 5.0.3 on 2024-03-22 21:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cursos", "0002_categoria_curso_duracion_curso_estado_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="curso",
            name="duracion",
            field=models.DurationField(default=datetime.timedelta(days=2)),
        ),
    ]
