# Generated by Django 5.0.3 on 2024-03-22 21:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cursos", "0003_alter_curso_duracion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="curso",
            name="duracion",
            field=models.DurationField(default=datetime.timedelta(days=2), null=True),
        ),
    ]
