# Generated by Django 5.0.3 on 2024-03-22 21:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cursos", "0005_alter_curso_duracion"),
    ]

    operations = [
        migrations.AddField(
            model_name="curso",
            name="destacado",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="curso",
            name="requisitos",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="curso",
            name="duracion",
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
