# Generated by Django 5.0.3 on 2024-04-12 20:26

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cursos", "0010_alter_estudiante_avatar_alter_instructor_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="curso",
            name="contenido",
            field=tinymce.models.HTMLField(default=""),
        ),
        migrations.AlterField(
            model_name="curso",
            name="descripcion",
            field=models.CharField(max_length=100),
        ),
    ]
